---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.5 enthält mehrere neue Funktionen und Verbesserungen. 
---
= Was ist neu in Cloud Volumes ONTAP 9.5
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.5 enthält mehrere neue Funktionen und Verbesserungen.


NOTE: Zusätzliche Funktionen und Verbesserungen sind auch in den neuesten Versionen von Cloud Manager eingeführt. Siehe https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["Versionshinweise Zu Cloud Manager"^] Entsprechende Details.



== 9.5 P11 (6. März 2020)

Der P11-Patch 9.5 für Cloud Volumes ONTAP ist nun über Cloud Manager 3.8 und höher erhältlich. Cloud Manager fordert Sie auf, Ihre vorhandenen Systeme auf diese Patch-Version zu aktualisieren. https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.5P11["Zeigen Sie die Liste der im P11-Patch fixierten Fehler an"^] (Anmeldung auf der NetApp Support Site erforderlich).



== 9.5 P10 (12. Januar 2020)

Der P10-Patch 9.5 für Cloud Volumes ONTAP ist nun über Cloud Manager erhältlich. Cloud Manager fordert Sie auf, Ihre vorhandenen Systeme auf diese Patch-Version zu aktualisieren. https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.5P10["Zeigen Sie die Liste der im P10-Patch fixierten Fehler an"^] (Anmeldung auf der NetApp Support Site erforderlich).



== 9.5 P9-Patch (17. November 2019)

Der P9-Patch 9.5 für Cloud Volumes ONTAP ist nun über Cloud Manager erhältlich. Cloud Manager fordert Sie auf, Ihre vorhandenen Systeme auf diese Patch-Version zu aktualisieren. https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.5P9["Zeigen Sie die Liste der im P9-Patch fixierten Fehler an"^] (Anmeldung auf der NetApp Support Site erforderlich).



== 9.5 P8 Patch (6. Oktober 2019)

Die 9.5 P8 Patch-Version für Cloud Volumes ONTAP ist jetzt verfügbar. Cloud Manager fordert Sie auf, Ihre vorhandenen Systeme auf diese Patch-Version zu aktualisieren. https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.5P8["Zeigen Sie die Liste der im P8-Patch fixierten Fehler an"^] (Anmeldung auf der NetApp Support Site erforderlich).



== 9.5 P6 Patch (16. Juli 2019)

Die 9.5 P6-Patch-Version für Cloud Volumes ONTAP ist jetzt verfügbar. Cloud Manager fordert Sie auf, Ihre vorhandenen Systeme auf diese Patch-Version zu aktualisieren. https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.5P6["Zeigen Sie die Liste der im P6-Patch fixierten Fehler an"^] (Anmeldung auf der NetApp Support Site erforderlich).


NOTE: Cloud Manager fordert Sie auf, auf bestimmte ONTAP-Patch-Releases mit wichtigen Fixes für Cloud Volumes ONTAP aufzurüsten. Aus diesem Grund können Sie in diesen Versionshinweisen eine Lücke zwischen Patch-Releases feststellen. Wir Listen nur die Patches auf, die Cloud Manager Ihnen zur Verfügung stellt.



== 9.5 P4-Patch (16. Mai 2019)

Das 9.5 P4-Patch-Release für Cloud Volumes ONTAP ist jetzt erhältlich. Cloud Manager fordert Sie auf, Ihre vorhandenen Systeme auf diese Patch-Version zu aktualisieren. https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.5P4["Hier finden Sie eine Liste der im P4-Patch fixierten Fehler"^] (Anmeldung auf der NetApp Support Site erforderlich).



== Unterstützung für die AWS C2S-Umgebung (2. Mai 2019)

Cloud Volumes ONTAP 9.5 und Cloud Manager 3.6.4 stehen jetzt den USA zur Verfügung Intelligence Community (IC) über die AWS Commercial Cloud Services Umgebung (C2S) Sie können HA-Paare und Single-Node-Systeme in C2S implementieren.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-getting-started-aws-c2s.html["Erste Schritte in der AWS C2S Umgebung"^]



== 9.5 P3-Patch (25. April 2019)

Der 9.5 P3-Patch für Cloud Volumes ONTAP ist jetzt verfügbar. https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.5P3["Zeigen Sie die Liste der im P3-Patch fixierten Fehler an"^] (Anmeldung auf der NetApp Support Site erforderlich).



== 9.5 P2 Patch (10. April 2019)

Das 9.5 P2 Patch Release für Cloud Volumes ONTAP ist jetzt erhältlich. Dieser Patch umfasst Bugfixes und unterstützt Flash Cache mit neuen AWS EC2 Instanztypen. Cloud Manager fordert Sie auf, Ihre vorhandenen Systeme auf diese Patch-Version zu aktualisieren.

https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.5P2["Klicken Sie hier, um die Fehler anzuzeigen, die im P2-Patch behoben wurden"^] (Anmeldung auf der NetApp Support Site erforderlich).



=== Flash Cache Unterstützung für neue EC2 Instanztypen

Die folgenden EC2-Instanztypen werden jetzt mit den Premium- und BYOL-Lizenzen unterstützt:

* C5d.4xlarge
* C5d.9xlarge
* R5d.2xlarge


Zu diesen Instanztypen gehört lokaler NVMe-Storage, der Cloud Volumes ONTAP als _Flash Cache_ verwendet. Flash Cache beschleunigt den Zugriff auf Daten durch intelligente Cache-Speicherung von kürzlich gelesenen Anwenderdaten und NetApp Metadaten in Echtzeit. Es bringt Vorteile bei Random Read-intensiven Workloads, einschließlich Datenbanken, E-Mail und File Services.

Um die Performance-Verbesserungen von Flash Cache nutzen zu können, muss die Komprimierung für alle Volumes deaktiviert sein. Beim Erstellen eines Volumes aus Cloud Manager kann keine Storage-Effizienz gewählt werden. Alternativ können Sie ein Volume erstellen und dann http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-vsmg/GUID-8508A4CB-DB43-4D0D-97EB-859F58B29054.html["Deaktivieren Sie die Datenkomprimierung über die CLI"^].


NOTE: Cloud Volumes ONTAP unterstützt das Neustarten des Cache nicht, wenn ein Neustart nach einem Neustart erfolgen soll.



== HA-Unterstützung in der Region Azure Central US (25. März 2019)

HA-Paare werden jetzt in der Region ZentralUS in Azure unterstützt.

https://cloud.netapp.com/cloud-volumes-global-regions["Eine vollständige Liste der unterstützten Azure Regionen ist verfügbar"^].



== 9.5 P1 Patch (18. März 2019)

Der 9.5 P1-Patch für Cloud Volumes ONTAP ist nun für alle Konfigurationen erhältlich. Cloud Manager fordert Sie auf, Ihre vorhandenen Systeme auf diese Patch-Version zu aktualisieren.

Wenn Sie ein vorhandenes HA-Paar in Azure haben, wird sich NetApp mit Ihnen in Verbindung setzen, um Sie bei der Anwendung des P1-Patch-Releases zu unterstützen.

https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.5P1["Klicken Sie hier, um die Fehler anzuzeigen, die im P1-Patch behoben wurden"^] (Anmeldung auf der NetApp Support Site erforderlich).



== Cloud Volumes ONTAP HA ist jetzt GA in Azure (18. März 2019)

Mit der Veröffentlichung des 9.5 P1-Patches sind HA-Paare in Azure nun allgemein verfügbar (GA). Eine Vorschau-Lizenz ist nicht mehr erforderlich.

Die GA-Version ist in den meisten Azure-Regionen mit Ausnahme der folgenden verfügbar:

* Zentral USA
* North Central USA
* US-Behörde Regionen
* Westen USA
* West Central USA


Eine Wartung in diesen Regionen kann die Erstellung von Cloud Volumes ONTAP verhindern und Failover-Prozesse verhindern. Wir planen, diese Regionen zu unterstützen, sobald die Wartung abgeschlossen ist.

https://cloud.netapp.com/cloud-volumes-global-regions["Eine vollständige Liste der unterstützten Azure Regionen ist verfügbar"^].



== 9.5 GA für AWS und Azure (4. Februar 2019)

Das GA-Release (General Availability, GA) von Cloud Volumes ONTAP 9.5 ist jetzt auch in AWS und Microsoft Azure verfügbar (nur für Single-Node-Systeme in Azure). Die GA-Version enthält Stabilitäts-Fixes, neue und veraltete Funktionen in AWS sowie eine Änderung an Kapazitätsgrenzen.



=== 368 TB Kapazitätsgrenze für alle Premium- und BYOL-Konfigurationen

Die Systemkapazitätsgrenze für Cloud Volumes ONTAP Premium und BYOL beträgt jetzt 368 TB für alle Konfigurationen: Single Node und HA in AWS und Azure.

Bei einigen Konfigurationen verhindern Festplattenlimits, dass Sie durch die Nutzung von Festplatten allein das Kapazitätslimit von 368 TB erreichen. In diesen Fällen erreichen Sie das Kapazitätslimit von 368 TB um https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["tiering inaktiver Daten in Objektspeicher"^]. Ein Single-Node-System in Azure könnte beispielsweise eine festplattenbasierte Kapazität von 252 TB aufweisen, sodass bis zu 116 TB inaktiver Daten im Azure Blob Storage genutzt werden können.

Weitere Informationen zu Festplattenlimits finden Sie unter link:reference-storage-limits.html["Storage-Beschränkungen"].



=== Unterstützung für M5- und R5-Instanzen in AWS

Cloud Volumes ONTAP unterstützt nun mehrere Instanztypen in den Serien M5 und R5:

[cols="4*"]
|===
| Entdecken | Standard | Premium | BYOL 


| m5.xlarge  a| 
* M5.2xlarge
* r5.xlarge

 a| 
* M5.4xlarge
* R5.2xlarge

 a| 
* m5.xlarge
* M5.2xlarge
* M5.4xlarge
* r5.xlarge
* R5.2xlarge


|===
Diese Instanzen verwenden einen Hypervisor, der auf KVM-Technologie basiert. Folglich unterstützen die Instanzen eine kleinere Anzahl an Datendisks als andere Instanztypen: Bis zu 24 Datendisks für Single-Node-Systeme und 21 Datendisks für HA-Paare. link:reference-storage-limits.html["Erfahren Sie mehr über Storage-Limits"].

Weitere Informationen zu https://aws.amazon.com/ec2/instance-types/m5/["M5 Instanzen"^] Und https://aws.amazon.com/ec2/instance-types/r5/["R5-Instanzen"^].



=== Unterstützung von NetApp Volume Encryption in AWS

https://www.netapp.com/us/media/ds-3899.pdf["NetApp Volume Encryption (NVE)"^] Ist eine softwarebasierte Technologie zur Verschlüsselung von Daten im Ruhezustand für ein Volume gleichzeitig. Daten, Snapshot Kopien und Metadaten sind verschlüsselt. Der Zugriff auf die Daten erfolgt über einen eindeutigen XTS-AES-256-Schlüssel, einen pro Volume.

Derzeit unterstützt Cloud Volumes ONTAP NetApp Volume Encryption mit einem externen Verschlüsselungsmanagement Server. Ein Onboard Key Manager wird nicht unterstützt. Die unterstützten Schlüsselmanager finden Sie im http://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool"^] Unter der *Key Manager*-Lösung.

Sie müssen NetApp Volume Encryption über die CLI einrichten. Die Verschlüsselung für bestimmte Volumes kann dann entweder über die CLI oder mit System Manager aktiviert werden. Cloud Manager unterstützt NetApp Volume Encryption von seiner Benutzeroberfläche und seinen APIs nicht.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-encrypting-volumes.html["Erfahren Sie, wie Sie NetApp Volume Encryption einrichten"^]


NOTE: NetApp Volume Encryption ist eine andere Verschlüsselungstechnologie als die Cloud Volumes ONTAP-Verschlüsselung, die Daten auf Aggregatebene verschlüsselt und jetzt veraltet ist. Ein Upgrade zwischen diesen beiden Verschlüsselungstechnologien ist nicht möglich. Siehe <<Veraltete Funktionen in AWS>> Finden Sie weitere Informationen.



=== Veraltete Funktionen in AWS

In Version 9.5 werden zwei Funktionen nicht mehr unterstützt.



==== Die Verschlüsselung auf Aggregatebene mit Cloud Volumes ONTAP unterstützt jetzt nur die native AWS Verschlüsselung von Festplatten

Die Verschlüsselung ruhender Daten bei Aggregaten mit externen Schlüsselmanagern wird nicht mehr unterstützt. Wenn Sie diese Funktion derzeit verwenden und aktualisieren möchten, müssen Sie ein neues 9.5-System starten und dann https://docs.netapp.com/us-en/bluexp-replication/task-replicating-data.html["Datenreplizierung"] Zu diesem System.

Die Verschlüsselung ruhender Daten wird mit anderen Methoden weiterhin unterstützt. Die Datenverschlüsselung erfolgt mithilfe der NetApp Volume Encryption oder mithilfe des AWS KMS (Key Management Service). https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-security.html["Weitere Informationen zur Verschlüsselung von Daten im Ruhezustand"^].



==== C4.2xlarge wird nicht mehr unterstützt

Der Instanztyp c4.2xlarge wird in Version 9.5 nicht unterstützt. Wenn Sie diesen Instanztyp verwenden, müssen Sie zuerst festlegen https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-ec2-instance.html["Wechseln Sie zu einem neuen Instanztyp"] Bevor Sie ein Upgrade auf Version 9.5 durchführen.



== 9.5 RC1 für Azure (4. Dezember 2018)

Cloud Volumes ONTAP 9.5 RC1 ist jetzt in Microsoft Azure verfügbar. Version 9.5 wird zu einem späteren Zeitpunkt in AWS verfügbar sein.



=== Vorschau von HA-Paaren in Microsoft Azure

Eine Vorschau auf Cloud Volumes ONTAP HA-Paare in Microsoft Azure ist jetzt verfügbar. Ein HA-Paar bietet Zuverlässigkeit der Enterprise-Klasse und unterbrechungsfreien Betrieb bei Ausfällen in der Cloud-Umgebung. Der Storage in einem Azure HA-Paar wird, ähnlich wie ein physischer ONTAP Cluster, von den beiden Nodes gemeinsam genutzt.

HA-Paare in Azure sind als Vorschau verfügbar. Sie können eine Preview-Lizenz anfordern, indem Sie sich an ng-Cloud-Volume-ONTAP-preview@netapp.com wenden.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-ha-azure.html["Erfahren Sie mehr über HA-Paare in Azure"^].



=== Verbesserte Netzwerk-Performance in Azure

Cloud Volumes ONTAP Systeme sind jetzt mit aktiviert https://docs.microsoft.com/en-us/azure/virtual-network/create-vm-accelerated-networking-cli["Beschleunigtes Networking"^] In Azure aus. Cloud Manager ermöglicht beschleunigte Netzwerke beim Upgrade auf 9.5 und bei der Bereitstellung neuer 9.5 Systeme.



=== Unterstützung für neue Azure Regionen

Sie können Cloud Volumes ONTAP jetzt auch in der Region Frankreich Central bereitstellen.



=== Unterstützung von NetApp Volume Encryption in Azure

https://www.netapp.com/us/media/ds-3899.pdf["NetApp Volume Encryption (NVE)"^] Ist eine softwarebasierte Technologie zur Verschlüsselung von Daten im Ruhezustand für ein Volume gleichzeitig. Daten, Snapshot Kopien und Metadaten sind verschlüsselt. Der Zugriff auf die Daten erfolgt über einen eindeutigen XTS-AES-256-Schlüssel, einen pro Volume.

Derzeit unterstützt Cloud Volumes ONTAP NetApp Volume Encryption mit einem externen Verschlüsselungsmanagement Server. Ein Onboard Key Manager wird nicht unterstützt. Die unterstützten Schlüsselmanager finden Sie im http://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool"^] Unter der *Key Manager*-Lösung.

Sie müssen NetApp Volume Encryption über die CLI einrichten. Die Verschlüsselung für bestimmte Volumes kann dann entweder über die CLI oder mit System Manager aktiviert werden. Cloud Manager bietet derzeit keine Unterstützung für NetApp Volume Encryption.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-encrypting-volumes.html["Erfahren Sie, wie Sie NetApp Volume Encryption einrichten"^]



== Upgrade-Hinweise

* Upgrades von Cloud Volumes ONTAP müssen von Cloud Manager abgeschlossen werden. Sie sollten kein Cloud Volumes ONTAP-Upgrade mit System Manager oder der CLI durchführen. Dies kann die Stabilität des Systems beeinträchtigen.
* Sie können ein Upgrade von Version 9.4 auf Cloud Volumes ONTAP 9.5 durchführen.
* Das Upgrade eines einzelnen Node-Systems nimmt das System für bis zu 25 Minuten offline, während dieser I/O-Unterbrechung erfolgt.
* Das Upgrade eines HA-Paars erfolgt unterbrechungsfrei und die I/O wird unterbrochen. Während dieses unterbrechungsfreien Upgrade-Prozesses wird jeder Node entsprechend aktualisiert, um den I/O-Datenverkehr für die Clients weiterhin bereitzustellen.

