---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, alarms, cloudwatch, giveback, govcloud, detaching, encryption, snapmanager, features, ha limitations, nfsv4, nfsv3, data tiering, disks, aggregates 
summary: Bekannte Einschränkungen identifizieren Plattformen, Geräte oder Funktionen, die von dieser Version des Produkts nicht unterstützt werden oder nicht korrekt mit dem Produkt zusammenarbeiten. Lesen Sie diese Einschränkungen sorgfältig durch. 
---
= Bekannte Einschränkungen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Bekannte Einschränkungen identifizieren Plattformen, Geräte oder Funktionen, die von dieser Version des Produkts nicht unterstützt werden oder nicht korrekt mit dem Produkt zusammenarbeiten. Lesen Sie diese Einschränkungen sorgfältig durch.



== Allgemeine Einschränkungen

Die folgenden Einschränkungen gelten für Cloud Volumes ONTAP in AWS und in Azure.



=== Maximal gleichzeitige Replizierungsvorgänge

Die maximale Anzahl gleichzeitiger SnapMirror oder SnapVault Transfers für Cloud Volumes ONTAP beträgt 100 pro Node, unabhängig vom Instanztyp oder Machine-Typ.



=== Software-Updates müssen von Cloud Manager abgeschlossen werden

Upgrades von Cloud Volumes ONTAP müssen von Cloud Manager abgeschlossen werden. Sie sollten kein Cloud Volumes ONTAP-Upgrade mit System Manager oder der CLI durchführen. Dies kann die Stabilität des Systems beeinträchtigen.



=== Die Cloud Volumes ONTAP-Bereitstellung darf nicht von der Konsole Ihres Cloud-Providers geändert werden

Änderungen an einer Cloud Volumes ONTAP Konfiguration aus der Konsole Ihres Cloud-Providers resultieren in einer nicht unterstützten Konfiguration. Alle Änderungen an den von Cloud Manager erstellten und gemanagten Cloud Volumes ONTAP Ressourcen können sich auf die Systemstabilität auswirken und das Management des Systems durch Cloud Manager vornehmen.



=== Festplatten und Aggregate müssen über Cloud Manager gemanagt werden

Alle Festplatten und Aggregate müssen direkt aus Cloud Manager erstellt und gelöscht werden. Sie sollten diese Aktionen nicht über ein anderes Management-Tool ausführen. Dies kann sich auf die Systemstabilität auswirken, die Fähigkeit zum Hinzufügen von Festplatten in der Zukunft beeinträchtigen und möglicherweise Kosten für redundante Cloud-Provider verursachen.



=== Einschränkung der SnapManager-Lizenzierung

SnapManager Lizenzen pro Server werden von Cloud Volumes ONTAP unterstützt. Lizenzen pro Storage-System (SnapManager Suite) werden nicht unterstützt.



=== Nicht unterstützte ONTAP-Funktionen

Die folgenden Funktionen werden mit Cloud Volumes ONTAP nicht unterstützt:

* Inline-Deduplizierung auf Aggregatebene
* Deduplizierung auf Aggregatebene im Hintergrund
* Disk Maintenance Center
* Festplattenbereinigung
* Fibre Channel (FC)
* Flash Pools
* FlexCache
* Unbegrenzte Volumes
* Interface Groups
* LIF-Failover bei Intranode
* MetroCluster
* Mandantenfähigkeit (es wird nur eine SVM für Daten unterstützt)
* RAID4, RAID-DP, RAID-TEC (RAID0 WIRD UNTERSTÜTZT)
* Service Processor
* SnapLock Compliance und Enterprise Mode (nur Cloud WORM wird unterstützt)
* SnapMirror Synchronous
* VLANs




== Bekannte Einschränkungen in AWS

Die folgenden bekannten Einschränkungen wirken sich auf Cloud Volumes ONTAP in AWS aus.



=== Einschränkungen für Flash Cache

Die Instanztypen C5D und R5D umfassen lokalen NVMe-Storage, der von Cloud Volumes ONTAP als _Flash Cache_ verwendet wird. Beachten Sie die folgenden Einschränkungen:

* Um die Performance-Verbesserungen von Flash Cache nutzen zu können, muss die Komprimierung für alle Volumes deaktiviert sein.
+
Beim Erstellen eines Volumes aus Cloud Manager kann keine Storage-Effizienz gewählt werden. Alternativ können Sie ein Volume erstellen und dann http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-vsmg/GUID-8508A4CB-DB43-4D0D-97EB-859F58B29054.html["Deaktivieren Sie die Datenkomprimierung über die CLI"^].

* Cloud Volumes ONTAP unterstützt das Neustarten des Cache nicht, wenn ein Neustart nach einem Neustart erfolgen soll.




=== Von Amazon CloudWatch gemeldete Fehlalarme

Cloud Volumes ONTAP gibt keine CPUs frei, wenn sie im Ruhezustand sind. Amazon CloudWatch kann also eine hohe CPU-Warnung für die EC2 Instanz melden, da sie eine Auslastung von 100 % aufweist. Sie können diesen Alarm ignorieren. Mit dem Befehl ONTAP Statistics wird die tatsächliche Nutzung der CPUs angezeigt.



=== Cloud Volumes ONTAP HA-Paare unterstützen kein sofortiges Storage-Giveback

Nach dem Neubooten eines Node muss der Partner die Daten synchronisieren, bevor er den Storage zurückgeben kann. Die Zeit, die für die Neusynchronisierung der Daten benötigt wird, hängt von der Menge der Daten ab, die von Clients geschrieben wurden, während der Node während des Giveback ausfällt und die Datenschreibgeschwindigkeit vorliegt.



=== Einschränkungen in der AWS C2S-Umgebung

Sehen Sie sich in der Dokumentation zu Cloud Manager an unter Einschränkungen: https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-aws-c2s.html["Erste Schritte in der AWS C2S Umgebung"^]



=== Einschränkungen in AWS GovCloud (USA) Regionen

* Cloud Manager muss in AWS GovCloud (USA) Regionen implementiert werden, um Cloud Volumes ONTAP Instanzen in jeder Region von AWS GovCloud (USA) starten zu können.
* Bei Implementierung in einer AWS GovCloud Region (US) können ONTAP Cluster in einer NetApp Private Storage für Microsoft Azure Konfiguration oder in einer NetApp Private Storage for SoftLayer Konfiguration nicht erkennen.




=== Das Trennen und Wiederverbinden von EBS-Volumes wird nicht unterstützt

Das Trennen eines EBS-Volumes von einer Cloud Volumes ONTAP-Instanz und das Wiederverbinden mit einer anderen Cloud Volumes ONTAP-Instanz wird nicht unterstützt. Daten sollten mit Cloud Manager zwischen Instanzen repliziert werden.



== Bekannte Einschränkungen in Microsoft Azure

Die folgenden bekannten Einschränkungen betreffen Cloud Volumes ONTAP in Azure.



=== Neue Implementierungen werden nicht unterstützt

Neue Implementierungen von Cloud Volumes ONTAP 9.5 werden in Azure nicht mehr unterstützt. Sie müssen Cloud Volumes ONTAP 9.7 implementieren.



=== HA-Einschränkungen

Die folgenden Einschränkungen betreffen Cloud Volumes ONTAP HA-Paare in Microsoft Azure:

* Daten-Tiering wird nicht unterstützt.
* NFSv4 wird nicht unterstützt. NFSv3 wird unterstützt.
* HA-Paare werden in einigen Regionen nicht unterstützt.
+
https://cloud.netapp.com/cloud-volumes-global-regions["Siehe die Liste der unterstützten Azure Regionen"^].


